# Generated by Django 3.2.13 on 2022-05-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.IntegerField()),
                ('fisrt_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=12)),
                ('root_size', models.CharField(max_length=12)),
                ('room_price', models.IntegerField()),
                ('is_aviable', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=255)),
                ('service_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group_id', models.IntegerField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.IntegerField()),
                ('guest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.guests')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.rooms')),
                ('service_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.service_group')),
            ],
        ),
    ]
