# Generated by Django 3.2.13 on 2022-05-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='root_size',
            new_name='room_size',
        ),
    ]
