# Generated by Django 3.2.13 on 2022-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_rename_root_size_rooms_room_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
